### ISSUE TITLE
Vue packages version mismatch

### ISSUE THREAD

**Issue by tfortier** [dangvanthanh/vue-ckeditor2#20]
I'm using laravel mix and added vue-ckeditor2 to my packages. When I run npm run dev to compile and webpack my files it works well untill I add this line :

`import Ckeditor from 'vue-ckeditor2';`

With only this import I start getting this error : 

```
ERROR  Failed to compile with 1 errors                                                                                                           10:18:59 AM

 error  in ./~/vue-ckeditor2/src/ckeditor.vue

Module build failed: Error:

Vue packages version mismatch:

- vue@2.0.8
- vue-template-compiler@2.3.0

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/home/runcloud/webapps/vixen/releases/1493216904/node_modules/vue-template-compiler/index.js:8:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/runcloud/webapps/vixen/releases/1493216904/node_modules/vue-loader/lib/parser.js:1:78)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/runcloud/webapps/vixen/releases/1493216904/node_modules/vue-loader/lib/loader.js:3:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/runcloud/webapps/vixen/releases/1493216904/node_modules/vue-loader/index.js:1:80)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

 @ ./resources/assets/js/app.js 26:0-37
 @ multi ./resources/assets/js/app.js
```

My versions are as follow : 

> vue@2.0.8
> laravel-mix@0.11.3
> vue-loader@12.0.2 (I also tried with vue-loader@11.3.4)
> vue-template-compiler@2.3.0
> ckeditor@4.6.2
> vue-ckeditor2@1.0.5

Also, here is my package.json file : 

```
{
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "dependencies": {
    "axios": "^0.15.2",
    "bootstrap": "^3.0.0",
    "ckeditor": "^4.6.2",
    "cross-env": "^3.2.3",
    "jquery": "^2.1.4",
    "js-cookie": "^2.1.0",
    "laravel-mix": "0.*",
    "moment": "^2.10.6",
    "promise": "^7.1.1",
    "sweetalert": "^1.1.3",
    "underscore": "^1.8.3",
    "urijs": "^1.17.0",
    "v-mask": "~1.1.1",
    "vue": "~2.0.8",
    "vue-ckeditor2": "~1.0.5",
    "webpack": "^2.3.2"
  }
}
```

**Comment by tfortier** [comment]
After a few head bang on on my desk I managed to have it work by modifing the package.json accordingly : 

```
"vue": "^2.0.8",
"vue-template-compiler": "^2.1.8",
```

Specifying those version numbers and the _^_ today results in this working. I'm no longer sure vue-ckeditor2 has anything to do with this error, but I'll leave my resolution here in the hope I'll save someone else the same headache.
